"""Run every query in queries/, save results to results/ and draw the summary charts."""

import sqlite3
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import pandas as pd

ROOT = Path(__file__).parent
DB_PATH = ROOT / "sp500.db"


def run_all(conn):
    results = {}
    sections = ["# Query results\n", "Generated by `run_queries.py`. Each section shows the question, then the output.\n"]
    for path in sorted((ROOT / "queries").glob("*.sql")):
        sql = path.read_text()
        df = pd.read_sql(sql, conn)
        results[path.stem] = df
        df.to_csv(ROOT / "results" / f"{path.stem}.csv", index=False)
        question = next(line[3:] for line in sql.splitlines() if line.startswith("-- Q"))
        sections.append(f"## {question}\n\n[`{path.name}`](../queries/{path.name})\n\n{df.to_markdown(index=False)}\n")
        print(f"{path.name:<35} {len(df):>3} rows")
    (ROOT / "results" / "README.md").write_text("\n".join(sections))
    return results


def draw_charts(results):
    plt.style.use("seaborn-v0_8-whitegrid")

    sectors = results["01_sector_composition"].sort_values("pct_of_index")
    fig, ax = plt.subplots(figsize=(9, 5.5))
    bars = ax.barh(sectors["sector"], sectors["pct_of_index"], color="#2f6db5")
    ax.bar_label(bars, fmt="%.1f%%", padding=3)
    ax.set_xlabel("Share of total index market value")
    ax.xaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_title("S&P 500 by sector: technology is almost 40% of the index")
    fig.savefig(ROOT / "images/sector_weights.png", dpi=120, bbox_inches="tight")

    decades = results["07_real_returns_by_decade"]
    fig, ax = plt.subplots(figsize=(11, 5))
    colors = ["#c0392b" if r < 0 else "#2f6db5" for r in decades["real_return_pa"]]
    bars = ax.bar(decades["decade"], decades["real_return_pa"], color=colors)
    ax.bar_label(bars, fmt="%.1f%%", padding=2, fontsize=9)
    ax.axhline(0, color="black", lw=0.8)
    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_ylabel("Real total return per year")
    ax.set_title("Inflation-adjusted S&P total return by decade (2020s = to mid-2023)")
    plt.xticks(rotation=45)
    fig.savefig(ROOT / "images/real_returns_by_decade.png", dpi=120, bbox_inches="tight")

    cape = results["09_cape_vs_future_returns"]
    labels = [f"Q{q}\nCAPE {r}" for q, r in zip(cape["cape_quintile"], cape["cape_range"])]
    fig, ax1 = plt.subplots(figsize=(10, 5))
    bars = ax1.bar(labels, cape["avg_real_price_return_10y_pa"], color="#2f6db5", label="Avg real price return, next 10 years")
    ax1.bar_label(bars, fmt="%.1f%%", padding=2)
    ax1.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax1.set_ylabel("Return per year")
    ax2 = ax1.twinx()
    ax2.plot(labels, cape["pct_of_months_losing_money_10y"], "o-", color="#c0392b", label="% of starts losing money over 10 years")
    ax2.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax2.set_ylim(0, 60)
    ax2.grid(False)
    ax1.set_title("Starting valuation vs the next 10 years (start dates 1881–2013)")
    handles = ax1.get_legend_handles_labels()[0] + ax2.get_legend_handles_labels()[0]
    ax1.legend(handles, [h.get_label() for h in handles], loc="upper right")
    fig.savefig(ROOT / "images/cape_vs_future_returns.png", dpi=120, bbox_inches="tight")


if __name__ == "__main__":
    with sqlite3.connect(DB_PATH) as conn:
        draw_charts(run_all(conn))
